{% set name = "mrtrix3" %}
{% set version = "3.0_RC3_latest" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_rev: {{ version }}
  git_url: https://github.com/MRtrix3/mrtrix3.git

requirements:
  build:
    - git
    - python >=2.7
    - eigen >=3.2
    - libtiff >=4.0
    - zlib 
    - fftw >=3.0
    - qt >=5.7
    - {{ compiler('cxx') }}
    - {{ cdt('xorg-x11-proto-devel') }}  # [linux]
    - {{ cdt('libx11-devel') }}          # [linux]
    - {{ cdt('libxext-devel') }}         # [linux]
    - {{ cdt('libxrender-devel') }}      # [linux]
    - {{ cdt('mesa-libgl-devel') }}      # [linux]
    - {{ cdt('mesa-libegl-devel') }}     # [linux]
    - {{ cdt('mesa-dri-drivers') }}      # [linux]
    - {{ cdt('libxau-devel') }}          # [linux]
    - {{ cdt('libselinux-devel') }}      # [linux]
    - {{ cdt('libxdamage') }}            # [linux]
    - {{ cdt('libxdamage-devel') }}      # [linux]
    - {{ cdt('libxfixes') }}             # [linux]
    - {{ cdt('libxfixes-devel') }}       # [linux]
    - {{ cdt('libxxf86vm') }}            # [linux]
    - {{ cdt('libxxf86vm-devel') }}      # [linux]

  run:
    - qt >=5.7
    - zlib 
    - libtiff >=4.0
    - fftw >=3.0

about:
  home: https://www.mrtrix.org
  license: https://github.com/MRtrix3/mrtrix3/blob/master/LICENCE.txt

